### ISSUE TITLE
So cool! Let us know if we can help while you hack on <model-viewer>

### ISSUE THREAD

**Issue by cdata** [FlorianFe/vox-viewer#1]
Hey @FlorianFe just saw your project on our used-by list. I got excited because it's one of the first cases I have seen of someone importing sub-modules of our library (as opposed to the entrypoint `@google/model-viewer`). LMK if I can answer any questions while you are hacking!

**Comment by FlorianFe** [comment]
Thank you very much =)
I'll ask you when I've got some questions!

**Comment by FlorianFe** [comment]
@cdata can you help me with issue #11 ? 
Maybe the issue lays in an misunderstanding of the model-viewer component from my side
