### ISSUE TITLE
Colors are too bright

### ISSUE THREAD

**Issue by FlorianFe** [FlorianFe/vox-viewer#11]
### What it looks like
<img width="867" alt="monu7_wrong" src="https://user-images.githubusercontent.com/19766850/115597807-f8c20580-a2d9-11eb-9a23-b579e1ef0f46.png">
The colors are too bright or the saturation is to low. Colors are looking way more grey'ish than they are defined. 

### How it should look like
<img width="867" alt="monu7_correct" src="https://sc.filehippo.net/images/t_app-cover-l,f_auto/p/0663f025-8444-4977-a084-a03b68d536f5/3870575166/magicavoxel-monu8.png"> 
is what it should look like. I'm not talking about the water and shadow effects of course.

**Comment by FlorianFe** [comment]
most probable the error lays in this lines 

        let vox = readVox(new Uint8Array(request.response));
      
        let voxelData = vox.xyzi.values;
        let size = vox.size;
        let rgba = vox.rgba.values;


        let componentizedColores = rgba.map((c) => [c.r, c.g, c.b])
        let voxels = zeros([size.x, size.y, size.z]);


        voxelData.forEach(({ x, y, z, i }) => voxels.set(x, y, z, i));


        voxels = voxels.transpose(1, 2, 0);


        let { vertices, normals, indices, voxelValues } = voxelTriangulation(voxels);


        let normalizedColors = componentizedColores.map((color) => color.map((c) => c / 2**8));
        let alignedColors = [ [0, 0, 0], ...normalizedColors ];
        let flattenedColors = flatten(voxelValues.map((v) => alignedColors[v]));


        let geometry = new BufferGeometry();


        geometry.setAttribute('position', new BufferAttribute(new Float32Array(vertices), 3));
        geometry.setAttribute('normal', new BufferAttribute(new Float32Array(normals), 3));
        geometry.setAttribute('color', new BufferAttribute(new Float32Array(flattenedColors), 3) );
        geometry.setIndex(new BufferAttribute(new Uint32Array(indices), 1));


        let material = new MeshStandardMaterial({ roughness: 1.0, metalness: 0.0 });
        let mesh = new Mesh(geometry, material);
        let exporter = new GLTFExporter();

**Comment by tarakoKutibiru** [comment]
Hi.
Thanks for the great npm package. I use these codes in my work and they are very helpful.

I have looked into this color issue in detail and found the problem and will share the information.

It appears to be a color space issue, and applying an inverse gamma correction to correct the difference in color space between MagicaVoxel and THREE.js works fine.

```
let normalizedColors = componentizedColores.map((color) => color.map((c) => c / this.MAX_VALUE_OF_A_BYTE));
        
for (let i = 0; i < normalizedColors.length; i++) {
    let r = normalizedColors[i][0];
    let g = normalizedColors[i][1];
    let b = normalizedColors[i][2];
    
    // Inverse gamma correction
    r = Math.pow(r, 2.2);
    g = Math.pow(g, 2.2);
    b = Math.pow(b, 2.2);
    
    normalizedColors[i][0] = r;
    normalizedColors[i][1] = g;
    normalizedColors[i][2] = b;
}
     
let alignedColors = [[0, 0, 0], ...normalizedColors];
let flattenedColors = flatten(voxelValues.map((v) => alignedColors[v]));
```

To make the problem easier to understand, I rendered the image using MeshBasicMaterial and it looks like this

■Before
![スクリーンショット 2022-05-26 17 49 42](https://user-images.githubusercontent.com/17213467/170453698-224fb99b-b4d1-46d9-a6ef-f9624e5cc2df.png)

■After
![スクリーンショット 2022-05-26 17 51 24](https://user-images.githubusercontent.com/17213467/170454042-fa970d50-03c0-4f13-b5b8-877afce56457.png)


This was the solution to the problem.
https://blenderartists.org/t/vertex-color-exported-by-gltf-glb-is-darker/1199970/4

**Comment by FlorianFe** [comment]
Awesome! It works! Thank you very much!
